---
# This playbook can be used to execute integration tests for
# the role located in:
#
# tests/integration/targets/dcnm_bootflash
#
# Modify the vars section with details for your testing setup.
#
# Usage
#
# ansible-playbook dcnm_tests.yaml -i ../dynamic_inventory_env.py
#
- hosts: ndfc
  gather_facts: no
  connection: ansible.netcommon.httpapi
  vars:
    # Uncomment ONE testcase to override environment variable ND_TESTCASE
    # testcase: dcnm_bootflash_deleted_specific
    # testcase: dcnm_bootflash_deleted_wildcard
    # testcase: dcnm_bootflash_query_specific
    # testcase: dcnm_bootflash_query_wildcard
    # Uncomment to override environment variable ND_USERNAME
    # switch_username: my_switch_username
    # Uncomment to override environment variable ND_PASSWORD
    # switch_password: my_switch_password
    # Uncomment to override environment variable ND_SWITCH_1_IP4
    # switch1: 10.1.1.1
    # Uncomment to override environment variable ND_SWITCH_2_IP4
    # switch2: 10.1.1.2
    # The vars below are included in the role's defaults/main.yaml
    # If it is desired to override the defaults, uncomment and
    # modify these.
    # switch1_file1: air.ndfc_ut
    # switch1_file2: earth.ndfc_ut
    # switch1_file3: fire.ndfc_ut
    # switch1_file4: water.ndfc_ut
    # switch2_file1: black.ndfc_ut
    # switch2_file2: blue.ndfc_ut
    # switch2_file3: green.ndfc_ut
    # switch2_file4: red.ndfc_ut
    # wildcard_filepath: "*:/*.ndfc_ut"

  roles:
    - dcnm_bootflash
